[package]
name = "blackout"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
image = "0.25.6"
pdfium-render = { version = "0.8.30" }
tqdm = "0.7.0"
